apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  containers:
  - name: pgadmin
    image: thajeztah/pgadmin4
    ports:
    - name: pgadmin-port
      containerPort: 5050
